name: roman_pointing_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - ipywidgets
  - numpy
  - scipy
  - matplotlib
  - astropy
  - notebook
  - pip
  - pip:
      - tqdm
      - ipympl
